# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171023_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('ra', models.IntegerField(db_column='RA', unique=True)),
                ('nome', models.CharField(db_column='Nome', max_length=120)),
                ('email', models.CharField(db_column='Email', max_length=80)),
                ('celular', models.CharField(blank=True, db_column='Celular', max_length=11, null=True)),
            ],
            options={
                'db_table': 'Aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arquivoquestao',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('arquivo', models.CharField(db_column='Arquivo', max_length=500, unique=True)),
            ],
            options={
                'db_table': 'ArquivoQuestao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arquivoresposta',
            fields=[
                ('idarquivoresposta', models.AutoField(db_column='IdArquivoResposta', primary_key=True, serialize=False)),
                ('arquivo', models.CharField(blank=True, db_column='Arquivo', max_length=500, null=True, unique=True)),
            ],
            options={
                'db_table': 'ArquivoResposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('carga_horaria', models.IntegerField()),
                ('professor', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('ativo', models.BooleanField()),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'core_curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursoturma',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CursoTurma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=240, unique=True)),
                ('teoria', models.DecimalField(db_column='Teoria', decimal_places=0, max_digits=3)),
                ('pratica', models.DecimalField(db_column='Pratica', decimal_places=0, max_digits=3)),
                ('cargahoraria', models.SmallIntegerField(db_column='CargaHoraria')),
                ('emenda', models.TextField(db_column='Emenda')),
                ('competencias', models.TextField(db_column='Competencias')),
                ('habilidades', models.TextField(db_column='Habilidades')),
                ('conteudo', models.TextField(db_column='Conteudo')),
                ('bibliografia_basica', models.TextField(blank=True, db_column='Bibliografia_basica', null=True)),
                ('bibliografia_complementar', models.TextField(blank=True, db_column='Bibliografia_complementar', null=True)),
            ],
            options={
                'db_table': 'Disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('ano', models.SmallIntegerField(db_column='Ano')),
                ('semestre', models.CharField(db_column='Semestre', max_length=1)),
            ],
            options={
                'db_table': 'DisciplinaOfertada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gradecurricular',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('ano', models.SmallIntegerField(blank=True, db_column='Ano', null=True)),
                ('semestre', models.CharField(blank=True, db_column='Semestre', max_length=1, null=True)),
            ],
            options={
                'db_table': 'GradeCurricular',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Matricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('numero', models.SmallIntegerField(db_column='Numero', unique=True)),
            ],
            options={
                'db_table': 'Periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periododisciplina',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PeriodoDisciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('ra', models.IntegerField(db_column='RA', unique=True)),
                ('nome', models.CharField(db_column='Nome', max_length=120)),
                ('email', models.CharField(db_column='Email', max_length=80)),
                ('celular', models.CharField(blank=True, db_column='Celular', max_length=11, null=True)),
                ('apelido', models.CharField(blank=True, db_column='Apelido', max_length=30, null=True, unique=True)),
            ],
            options={
                'db_table': 'Professor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, db_column='Numero', null=True, unique=True)),
                ('data_limite_entrega', models.CharField(blank=True, max_length=10, null=True)),
                ('descricao', models.TextField(blank=True, db_column='Descricao', null=True)),
                ('data', models.CharField(db_column='Data', max_length=10)),
            ],
            options={
                'db_table': 'Questao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('raaluno', models.IntegerField(db_column='RaAluno', unique=True)),
                ('data_avaliacao', models.CharField(db_column='Data_Avaliacao', max_length=10)),
                ('nota', models.DecimalField(blank=True, db_column='Nota', decimal_places=2, max_digits=4, null=True)),
                ('avaliacao', models.TextField(blank=True, db_column='Avaliacao', null=True)),
                ('descricao', models.TextField(blank=True, db_column='Descricao', null=True)),
                ('data_de_envio', models.CharField(blank=True, db_column='Data_de_Envio', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Resposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=1, unique=True)),
                ('turno', models.CharField(blank=True, db_column='Turno', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Turma',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'managed': False},
        ),
    ]
