# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171111_1440'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='curso',
            table='Curso',
        ),
    ]
